language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '10'
  - '9'
  - '8'
  - '6'
after_success:
  - npm run report-coverage
branches:
  except:
    - /^v\d+\.\d+\.\d+$/

jobs:
  include:
    - stage: greenkeeper
      before_install: npm install -g greenkeeper-lockfile
      install: npm install
      before_script: greenkeeper-lockfile-update
      after_script: greenkeeper-lockfile-upload

    - stage: semantic release
      node_js: '10'
      script: npm run semantic-release

stages:
  - name: compile
  - name: test
    if: NOT branch =~ /^greenkeeper\/.*$/
  - name: greenkeeper
    if: branch =~ /^greenkeeper\/.*$/
  - name: semantic release
    if: branch = master
